### ISSUE TITLE
Navigate to highlighted code doesn't work

### ISSUE THREAD

**Issue by batopa** [ApiGen/ThemeBootstrap#5]
Clicking on property or method to see highlighted code shows the file code but not navigate to highlighted code. The url contain correctly hash tag with line numbers.

Testing using apigen 4.1-beta.
All work properly with default theme.

_I don't know if it's an issue of theme or of apigen so sorry if I have opened the issue in the wrong place._

**Comment by olvlvl** [comment]
Thanks for your bug report. You're right, the code is correctly highlighted bu the browser doesn't navigate to it. That's because the highlighted code use hash `#16-24` to highlight lines from 16 to 24, but only anchors `#16`, … `#24` are defined. I need to check the default theme to see how it works there.

**Comment by TomasVotruba** [comment]
@olvlvl Thanks for your care. I thinks it's related to this part in [main.js](https://github.com/ApiGen/ThemeDefault/blob/61da5cd2198da93ea3f4ea88fc661575047a130e/src/js/main.js#L214)

**Comment by batopa** [comment]
I have done a pull request https://github.com/ApiGen/ThemeBootstrap/pull/6

**Comment by olvlvl** [comment]
Thanks!

**Comment by TomasVotruba** [comment]
Thank you! Merged
